import PDFDocument from 'pdfkit'

// Render the agent's result into a clean, readable PDF and return it as a Buffer.
// Understands a small Markdown subset: # / ## headings, - or • bullets,
// 1. numbered lists, **bold**, and blank-line paragraph breaks.
export function generateResultPdf(goal: string, summary: string): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ size: 'A4', margin: 56 })
    const chunks: Buffer[] = []

    doc.on('data', (c) => chunks.push(c as Buffer))
    doc.on('end', () => resolve(Buffer.concat(chunks)))
    doc.on('error', reject)

    const INK = '#1a1a2e'
    const MUTED = '#6b7280'
    const ACCENT = '#4f46e5'

    // ── Header ──
    doc.fillColor(ACCENT).fontSize(22).font('Helvetica-Bold').text('Equilibrium')
    doc.moveDown(0.1)
    doc.fillColor(MUTED).fontSize(10).font('Helvetica').text('AI Agent Report')
    doc
      .moveTo(doc.x, doc.y + 6)
      .lineTo(doc.page.width - 56, doc.y + 6)
      .strokeColor('#e5e7eb')
      .lineWidth(1)
      .stroke()
    doc.moveDown(1)

    // ── Goal + date ──
    doc.fillColor(MUTED).fontSize(9).font('Helvetica-Bold').text('GOAL')
    doc.moveDown(0.2)
    doc.fillColor(INK).fontSize(12).font('Helvetica').text(goal)
    doc.moveDown(0.4)
    doc
      .fillColor(MUTED)
      .fontSize(9)
      .text(`Generated ${new Date().toLocaleString()}`)
    doc.moveDown(1)

    // ── Body (markdown subset) ──
    const renderInline = (line: string, opts: PDFKit.Mixins.TextOptions = {}) => {
      // Split on **bold** and render runs, keeping them on one line.
      const parts = line.split(/(\*\*[^*]+\*\*)/g).filter(Boolean)
      parts.forEach((part, i) => {
        const bold = part.startsWith('**') && part.endsWith('**')
        const text = bold ? part.slice(2, -2) : part
        doc
          .font(bold ? 'Helvetica-Bold' : 'Helvetica')
          .fillColor(INK)
          .text(text, { continued: i < parts.length - 1, ...opts })
      })
    }

    const lines = summary.replace(/\r/g, '').split('\n')
    for (const raw of lines) {
      const line = raw.trimEnd()

      if (!line.trim()) {
        doc.moveDown(0.5)
        continue
      }
      // Skip stray Markdown code fences (```).
      if (/^```/.test(line.trim())) continue
      if (line.startsWith('### ')) {
        doc.moveDown(0.3)
        doc.fillColor(INK).fontSize(12).font('Helvetica-Bold').text(line.slice(4))
        doc.moveDown(0.15)
        continue
      }
      if (line.startsWith('## ')) {
        doc.moveDown(0.4)
        doc.fillColor(INK).fontSize(13).font('Helvetica-Bold').text(line.slice(3))
        doc.moveDown(0.2)
        continue
      }
      if (line.startsWith('# ')) {
        doc.moveDown(0.5)
        doc.fillColor(INK).fontSize(15).font('Helvetica-Bold').text(line.slice(2))
        doc.moveDown(0.2)
        continue
      }

      const bullet = line.match(/^[-•*]\s+(.*)$/)
      if (bullet) {
        doc.fontSize(11)
        doc.font('Helvetica').fillColor(ACCENT).text('•  ', { continued: true })
        renderInline(bullet[1], { indent: 0 })
        doc.moveDown(0.15)
        continue
      }

      const numbered = line.match(/^(\d+)\.\s+(.*)$/)
      if (numbered) {
        doc.fontSize(11)
        doc.font('Helvetica-Bold').fillColor(ACCENT).text(`${numbered[1]}.  `, { continued: true })
        renderInline(numbered[2])
        doc.moveDown(0.15)
        continue
      }

      doc.fontSize(11)
      renderInline(line)
      doc.moveDown(0.3)
    }

    // ── Footer ──
    doc.moveDown(2)
    doc
      .fillColor(MUTED)
      .fontSize(8)
      .font('Helvetica')
      .text('Generated by Equilibrium AI Agent', { align: 'center' })

    doc.end()
  })
}
